"use client";
import { useEffect, useMemo, useState } from "react";
import { collection, getDocs, updateDoc, doc, orderBy, query, deleteDoc } from "firebase/firestore";
import { db, firebaseConfigured } from "@/lib/firebase";
import { useAuth } from "@/lib/auth";
import SignalForm from "@/components/SignalForm";

function csvDownload(name: string, rows: any[]) {
  const headers = Array.from(new Set(rows.flatMap(r => Object.keys(r))));
  const body = [headers.join(","), ...rows.map(r => headers.map(h => JSON.stringify(r[h] ?? "")).join(","))].join("\n");
  const blob = new Blob([body], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url);
}

export default function Admin(){
 const {profile,loading}=useAuth();
 const [users,setUsers]=useState<any[]>([]); const [regs,setRegs]=useState<any[]>([]); const [payments,setPayments]=useState<any[]>([]); const [signals,setSignals]=useState<any[]>([]); const [tab,setTab]=useState("overview");
 async function load(){if(!firebaseConfigured||!db) return; const u=await getDocs(collection(db,"users")); setUsers(u.docs.map(d=>({id:d.id,...d.data()}))); const r=await getDocs(query(collection(db,"registrations"),orderBy("createdAt","desc"))); setRegs(r.docs.map(d=>({id:d.id,...d.data()}))); const p=await getDocs(query(collection(db,"payments"),orderBy("createdAt","desc"))); setPayments(p.docs.map(d=>({id:d.id,...d.data()}))); const s=await getDocs(query(collection(db,"signals"),orderBy("createdAt","desc"))); setSignals(s.docs.map(d=>({id:d.id,...d.data()})));}
 useEffect(()=>{ if(profile?.role==="admin"||profile?.role==="superAdmin") load();},[profile]);
 const stats = useMemo(()=>({ pending: payments.filter(x=>x.status==='pending').length, verified: payments.filter(x=>x.status==='verified').length, premium: users.filter(x=>x.courseAccess && x.courseAccess !== 'none').length }),[payments,users]);
 if(loading) return <main className="p-8">Loading...</main>;
 if(profile?.role!=="admin"&&profile?.role!=="superAdmin") return <main className="mx-auto max-w-xl px-4 py-14"><h1 className="text-3xl font-bold text-red-300">Admin access required</h1><p className="mt-3 text-slate-300">For first setup, open Firestore → users → your user document → change role from user to admin.</p></main>;
 async function grant(uid:string, access="premium"){if(!db) return; await updateDoc(doc(db,"users",uid),{courseAccess:access,paymentStatus:"verified",status:"active",updatedAt:new Date().toISOString()}); await load();}
 async function setPayment(id:string,status:string,userId?:string){if(!db) return; await updateDoc(doc(db,"payments",id),{status,verifiedAt: status==='verified'?new Date().toISOString():null}); if(userId && status==='verified') await grant(userId,"premium"); else await load();}
 async function setReg(id:string,status:string){if(!db) return; await updateDoc(doc(db,"registrations",id),{status,updatedAt:new Date().toISOString()}); await load();}
 async function signalStatus(id:string,status:string){if(!db) return; await updateDoc(doc(db,"signals",id),{status,updatedAt:new Date().toISOString()}); await load();}
 async function removeSignal(id:string){if(!db || !confirm("Delete this signal?")) return; await deleteDoc(doc(db,"signals",id)); await load();}
 return <main className="mx-auto max-w-7xl px-4 py-10"><h1 className="text-4xl font-black">Admin Panel</h1><p className="mt-2 text-slate-400">Manage users, registrations, payments, course access, and signals.</p>
 <div className="mt-8 flex flex-wrap gap-2">{["overview","users","registrations","payments","signals"].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"btn-green":"btn-dark"}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==="overview"&&<section className="mt-8 grid gap-5 md:grid-cols-5"><div className="card"><b>Total Users</b><p className="text-3xl text-green-400">{users.length}</p></div><div className="card"><b>Registrations</b><p className="text-3xl text-green-400">{regs.length}</p></div><div className="card"><b>Pending Payments</b><p className="text-3xl text-green-400">{stats.pending}</p></div><div className="card"><b>Verified Payments</b><p className="text-3xl text-green-400">{stats.verified}</p></div><div className="card"><b>Signals</b><p className="text-3xl text-green-400">{signals.length}</p></div></section>}
 {tab==="users"&&<section className="mt-8"><button className="btn-dark mb-4" onClick={()=>csvDownload('users.csv',users)}>Export Users CSV</button><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900"><tr><th className="p-3 text-left">Name</th><th>Email</th><th>Role</th><th>Status</th><th>Access</th><th>Payment</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr className="border-t border-slate-800" key={u.id}><td className="p-3">{u.fullName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.status}</td><td>{u.courseAccess}</td><td>{u.paymentStatus}</td><td className="space-x-2"><button className="btn-green px-3 py-2" onClick={()=>grant(u.id,'premium')}>Grant Premium</button><button className="btn-dark px-3 py-2" onClick={()=>grant(u.id,'none')}>Remove</button></td></tr>)}</tbody></table></div></section>}
 {tab==="registrations"&&<section className="mt-8"><button className="btn-dark mb-4" onClick={()=>csvDownload('registrations.csv',regs)}>Export Registrations CSV</button><div className="grid gap-4">{regs.map(r=><div className="card" key={r.id}><div className="flex flex-wrap items-center justify-between gap-3"><b>{r.fullName}</b><select className="input max-w-xs" value={r.status} onChange={e=>setReg(r.id,e.target.value)}><option>New</option><option>Contacted</option><option>Payment Pending</option><option>Payment Verified</option><option>Access Granted</option><option>Rejected</option></select></div><p className="mt-2 text-slate-300">{r.email} | {r.phone}</p><p>{r.preferredCourse} | {r.learningMode} | {r.learningStyle} | {r.paymentMethod}</p><p className="text-slate-400">{r.message}</p></div>)}</div></section>}
 {tab==="payments"&&<section className="mt-8"><button className="btn-dark mb-4" onClick={()=>csvDownload('payments.csv',payments)}>Export Payments CSV</button><div className="grid gap-4">{payments.map(p=><div className="card" key={p.id}><div className="flex flex-wrap items-center justify-between gap-3"><b>{p.courseType} — {p.amount} {p.currency}</b><span className="text-green-300">{p.status}</span></div><p className="mt-2">Method: {p.paymentMethod} | Txn: {p.transactionId || '-'}</p>{p.paymentProofUrl&&<a className="text-green-300 underline" href={p.paymentProofUrl} target="_blank">View Proof</a>}<div className="mt-4 flex gap-2"><button className="btn-green" onClick={()=>setPayment(p.id,'verified',p.userId)}>Verify & Grant</button><button className="btn-dark" onClick={()=>setPayment(p.id,'rejected',p.userId)}>Reject</button></div></div>)}</div></section>}
 {tab==="signals"&&<section className="mt-8 grid gap-6"><SignalForm onSaved={load}/><div className="grid gap-4">{signals.map(s=><div className="card" key={s.id}><div className="flex flex-wrap items-center justify-between gap-3"><b>{s.title}</b><span>{s.visibility} | {s.status}</span></div><p className="mt-2 text-slate-300">{s.marketType} | {s.pair} | {s.direction}</p><p className="text-slate-400">{s.analysisText}</p><div className="mt-4 flex flex-wrap gap-2"><select className="input max-w-xs" value={s.status} onChange={e=>signalStatus(s.id,e.target.value)}><option>Active</option><option>Educational Setup</option><option>TP1 Hit</option><option>TP2 Hit</option><option>TP3 Hit</option><option>Stop Loss Hit</option><option>Break Even</option><option>Cancelled</option><option>Closed Manually</option></select><button className="btn-dark" onClick={()=>removeSignal(s.id)}>Delete</button></div></div>)}</div></section>}
 </main>}
