"use client";
import { useEffect, useState } from "react";
import { collection, getDocs, updateDoc, doc } from "firebase/firestore";
import { db, firebaseConfigured } from "@/lib/firebase";
import { useAuth } from "@/lib/auth";

export default function Admin(){const {profile,loading}=useAuth(); const [users,setUsers]=useState<any[]>([]); const [regs,setRegs]=useState<any[]>([]);
 useEffect(()=>{async function load(){if(!firebaseConfigured||!db) return; const u=await getDocs(collection(db,"users")); setUsers(u.docs.map(d=>({id:d.id,...d.data()}))); const r=await getDocs(collection(db,"registrations")); setRegs(r.docs.map(d=>({id:d.id,...d.data()})))} if(profile?.role==="admin"||profile?.role==="superAdmin") load();},[profile]);
 if(loading) return <main className="p-8">Loading...</main>; if(profile?.role!=="admin"&&profile?.role!=="superAdmin") return <main className="mx-auto max-w-xl px-4 py-14"><h1 className="text-3xl font-bold text-red-300">Admin access required</h1><p className="mt-3 text-slate-300">Set admin role in Firestore manually for first setup or use custom claims in production.</p></main>;
 async function grant(uid:string){if(!firebaseConfigured||!db) return alert("Firebase environment variables are missing in Netlify."); await updateDoc(doc(db,"users",uid),{courseAccess:"premium",paymentStatus:"verified",updatedAt:new Date().toISOString()}); alert("Access granted. Refresh page.")}
 return <main className="mx-auto max-w-7xl px-4 py-14"><h1 className="text-4xl font-black">Admin Panel</h1><section className="mt-8 grid gap-5 md:grid-cols-4"><div className="card"><b>Total Users</b><p className="text-3xl text-green-400">{users.length}</p></div><div className="card"><b>Registrations</b><p className="text-3xl text-green-400">{regs.length}</p></div><div className="card"><b>Pending Payments</b><p className="text-3xl text-green-400">{users.filter(x=>x.paymentStatus==='pending').length}</p></div><div className="card"><b>Verified</b><p className="text-3xl text-green-400">{users.filter(x=>x.paymentStatus==='verified').length}</p></div></section><h2 className="mt-10 text-2xl font-bold">Users</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900"><tr><th className="p-3 text-left">Name</th><th>Email</th><th>Role</th><th>Access</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr className="border-t border-slate-800" key={u.id}><td className="p-3">{u.fullName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.courseAccess}</td><td><button className="btn-green px-3 py-2" onClick={()=>grant(u.id)}>Grant Premium</button></td></tr>)}</tbody></table></div><h2 className="mt-10 text-2xl font-bold">Registrations</h2><div className="mt-4 grid gap-4">{regs.map(r=><div className="card" key={r.id}><b>{r.fullName}</b><p>{r.preferredCourse} | {r.learningMode} | {r.paymentMethod}</p><p className="text-slate-400">{r.message}</p></div>)}</div></main>}
