"use client";
import { useState } from "react";
import { addDoc, collection } from "firebase/firestore";
import { db, firebaseConfigured } from "@/lib/firebase";
import { useAuth } from "@/lib/auth";

export default function RegisterForm(){const {user,profile}=useAuth(); const [msg,setMsg]=useState(""); const [f,setF]=useState({experienceLevel:"Beginner",preferredCourse:"Online Course — $100",learningMode:"One-to-One Learning",learningStyle:"Online",preferredTimeSlot:"",paymentMethod:"Cash",paymentReference:"",message:""});
 async function submit(e:React.FormEvent){e.preventDefault(); if(!firebaseConfigured||!db){setMsg("Firebase environment variables are missing. Add NEXT_PUBLIC_FIREBASE_* keys in Vercel."); return;} if(!user||!profile){setMsg("Please login first."); return;} setMsg("Submitting..."); const now=new Date().toISOString(); await addDoc(collection(db,"registrations"),{userId:user.uid,fullName:profile.fullName,email:profile.email,phone:profile.phone||"",country:profile.country||"",city:profile.city||"",...f,status:"New",createdAt:now,updatedAt:now}); setMsg("Registration submitted. Admin will review your request.")}
 return <form onSubmit={submit} className="card mt-8 grid gap-4"><select className="input" onChange={e=>setF({...f,experienceLevel:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select className="input" onChange={e=>setF({...f,preferredCourse:e.target.value})}><option>Online Course — $100</option><option>Physical Course — $150</option></select><select className="input" onChange={e=>setF({...f,learningMode:e.target.value})}><option>One-to-One Learning</option><option>Batch Learning</option></select><select className="input" onChange={e=>setF({...f,learningStyle:e.target.value})}><option>Online</option><option>Physical</option></select><input className="input" placeholder="Preferred Time Slot" onChange={e=>setF({...f,preferredTimeSlot:e.target.value})}/><select className="input" onChange={e=>setF({...f,paymentMethod:e.target.value})}><option>Cash</option><option>Easypaisa</option><option>JazzCash</option><option>Bank Transfer</option><option>Crypto / USDT</option></select><input className="input" placeholder="Transaction ID optional" onChange={e=>setF({...f,paymentReference:e.target.value})}/><textarea className="input min-h-28" placeholder="Message / Questions" onChange={e=>setF({...f,message:e.target.value})}/><button className="btn-green">Submit Registration</button>{msg&&<p className="text-slate-300">{msg}</p>}</form>}
