import {addDoc,collection,deleteDoc,doc,getDoc,getDocs,limit,orderBy,query,serverTimestamp,setDoc,updateDoc,where} from "firebase/firestore";import {db} from "./firebase";import {Signal} from "./types";
export async function addRegistration(data:any){return addDoc(collection(db,"registrations"),{...data,status:"New",createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function addTicket(data:any){return addDoc(collection(db,"supportTickets"),{...data,status:"Open",createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}export async function addInquiry(data:any){return addDoc(collection(db,"accountManagementInquiries"),{...data,status:"New",createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function createSignal(data:Signal){return addDoc(collection(db,"signals"),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}export async function updateSignal(id:string,data:Partial<Signal>){return updateDoc(doc(db,"signals",id),{...data,updatedAt:serverTimestamp(),...(data.status&&data.status!=="Active"?{closedAt:serverTimestamp()}: {})})}export async function deleteSignal(id:string){return deleteDoc(doc(db,"signals",id))}
export async function listPublicSignals(){const s=await getDocs(query(collection(db,"signals"),where("visibility","==","public"),orderBy("createdAt","desc"),limit(50)));return s.docs.map(d=>({id:d.id,...d.data()})) as Signal[]}
export async function listAccessibleSignals(user:any,profile:any){const s=await getDocs(query(collection(db,"signals"),orderBy("createdAt","desc"),limit(100)));const all=s.docs.map(d=>({id:d.id,...d.data()})) as Signal[];return all.filter(x=>x.visibility==="public"||user&&(x.visibility==="loggedIn"||x.visibility==="premium"&&["premium","online","physical"].includes(profile?.courseAccess)||x.visibility==="selected"&&x.selectedUserIds?.includes(user.uid)))}
export function calcStats(signals:Signal[]){const closed=signals.filter(s=>!["Active","Educational Setup"].includes(s.status));const wins=closed.filter(s=>s.status.startsWith("TP")).length;const losses=closed.filter(s=>s.status==="Stop Loss Hit").length;const be=closed.filter(s=>s.status==="Break Even").length;const can=closed.filter(s=>s.status==="Cancelled").length;const counted=closed.filter(s=>!["Cancelled","Closed Manually"].includes(s.status)).length;return{total:signals.length,active:signals.filter(s=>s.status==="Active").length,closed:closed.length,wins,losses,be,can,winRate:counted?wins/counted*100:0,lossRate:counted?losses/counted*100:0}}
export async function getOrCreateDemo(uid:string){const ref=doc(db,"demoAccounts",uid);const s=await getDoc(ref);if(s.exists())return s.data();const data={userId:uid,startingBalance:10000,currentBalance:10000,totalPnL:0,totalTrades:0,winningTrades:0,losingTrades:0,breakEvenTrades:0,winRate:0,status:"active",createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(ref,data);return data}
export async function addDemoTrade(data:any){return addDoc(collection(db,"demoTrades"),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}export async function addJournal(data:any){return addDoc(collection(db,"tradingJournals"),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}export async function saveSettings(data:any){return setDoc(doc(db,"websiteSettings","main"),{...data,updatedAt:serverTimestamp()},{merge:true})}
