"use client";
import { useState } from "react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useAuth } from "@/lib/auth";

export default function AccountManagementPage(){
  const { user, profile } = useAuth(); const [msg,setMsg]=useState(""); const [form,setForm]=useState({inquiryType:"Account Management", capitalRange:"Below $500", tradingExperience:"Beginner", facedLosses:"No", message:""});
  async function submit(){ if(!db || !user) return setMsg("Please login first."); await addDoc(collection(db,"accountManagementInquiries"),{userId:user.uid, fullName:profile?.fullName||"", email:user.email||"", phone:profile?.phone||"", country:profile?.country||"", city:profile?.city||"", ...form, status:"New", createdAt:serverTimestamp(), updatedAt:serverTimestamp()}); setMsg("Inquiry submitted. Admin will review manually."); setForm({...form,message:""}); }
  return <main className="mx-auto max-w-4xl px-4 py-10"><h1 className="text-3xl font-black">Account Management & Investment Interest</h1><p className="mt-3 text-slate-300">This is only an inquiry workflow. No profit, fixed return, fee recovery, or loss recovery is guaranteed.</p><div className="card mt-8 space-y-3">{msg&&<p className="text-green-300">{msg}</p>}<select className="input" value={form.inquiryType} onChange={e=>setForm({...form,inquiryType:e.target.value})}>{["Account Management","Investment Partnership","Profit-Sharing Discussion","Loss Recovery Guidance","General Consultation"].map(x=><option key={x}>{x}</option>)}</select><select className="input" value={form.capitalRange} onChange={e=>setForm({...form,capitalRange:e.target.value})}>{["Below $500","$500 - $1,000","$1,000 - $5,000","$5,000 - $10,000","Above $10,000"].map(x=><option key={x}>{x}</option>)}</select><select className="input" value={form.tradingExperience} onChange={e=>setForm({...form,tradingExperience:e.target.value})}>{["Beginner","Intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</select><select className="input" value={form.facedLosses} onChange={e=>setForm({...form,facedLosses:e.target.value})}><option>Yes</option><option>No</option></select><textarea className="input min-h-32" placeholder="Message / details" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className="btn-green" onClick={submit}>Submit Inquiry</button></div></main>
}
